### ISSUE TITLE
i have questions

### ISSUE THREAD

**Issue by threadexio** [SteliosLL/coc#1]
- what the hell it this repo?
- why does it exist?
- why did i star it?

**Comment by SteliosLL** [comment]
> * what the hell it this repo?
> * why does it exist?
> * why did i star it?

no one will ever know why this repo exists and why you starred it

**Comment by threadexio** [comment]
you answered all of my questions.

Closing the issue

**Comment by SteliosLL** [comment]
> you answered all of my questions.
> 
> Closing the issue

**Hi please send the link for the stupid haxor server owned by lauri and the dumb anaoo**
